<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>s</string>
		<string>sns</string>
		<string>snes</string>
		<string>asm</string>
		<string>inc</string>
	</array>
	<key>foldingStartMarker</key>
	<string>^[a-zA-Z0-9_]+:\s*$</string>
	<key>foldingStopMarker</key>
	<string>^[^"\r\n];$</string>
	<key>name</key>
	<string>SNES</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(?i:(adc|and|asl|bcc|bcs|beq|bit|bmi|bne|bpl|bra|brl|brk|bvc|bvs|clc|cld|cli|clv|cmp|cop|cpa|cpx|cpy|dea|dec|dex|dey|eor|ina|inc|inx|iny|jml|jmp|jsl|jsr|lda|ldx|ldy|lsr|mvn|mvp|nop|ora|pea|pei|per|pha|phb|phd|php|phk|phx|phy|pla|plb|pld|plp|plx|ply|rep|rol|ror|rti|rtl|rts|sbc|sec|sed|sei|sep|sta|stp|stx|sty|stz|tax|tay|tcd|tcs|tdc|trb|tsb|tsc|tsx|txa|txs|txy|tya|tyx|wai|wdm|xba|xce))\b</string>
			<key>name</key>
			<string>source.snes.constant.op-codes</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:(a|x|y))\b</string>
			<key>name</key>
			<string>source.snes.constant.register</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:(arch|print|s(cope|ize|e(ction|gment)|lot(size)?)|h(irom|ea(der_off|p)|rom)|co(de|mputesneschecksum)|i(16|nc(lude|bin|src)|8|f(ndef|def)?|mport(zp)?)|zeropage|org|d(c(w|b)|ef(ine|aultslot)|w|b)|unpack|e(nd(s(cope)?|if|rep(eat)?|m(e|acro))|qu|lse(if)?|xport(zp)?|mptyfill)|word|l(ocal|rom)|a(sciiz|16|8)|r(o(data|mbanks(ize)?)|e(s|peat))|global(zp)?|m(emorymap|acro)|b(ss|yte|a(seadress|nk))))\b</string>
			<key>name</key>
			<string>source.snes.constant.types</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:(snes\.cpu))\b</string>
			<key>name</key>
			<string>source.snes.constant.values</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[^"\r\n][a-zA-Z0-9_]+:</string>
			<key>name</key>
			<string>source.snes.function</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>{</string>
			<key>end</key>
			<string>}</string>
			<key>name</key>
			<string>source.snes.define</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(//).*?($\n?|(?=\?&gt;))</string>
			<key>name</key>
			<string>source.snes.comment.double-slash</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(;).*$\n?</string>
			<key>name</key>
			<string>source.snes.comment.semi-colon</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment-block</key>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.snes</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.snes</string>
		</dict>
		<key>comment-double-slash</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.snes</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(//).*?($\n?|(?=\?&gt;))</string>
			<key>name</key>
			<string>comment.line.double-slash.snes</string>
		</dict>
		<key>comment.semi-colon</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.snes</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(;).*$\n?</string>
			<key>name</key>
			<string>comment.line.semi-colon.snes</string>
		</dict>
		<key>string-double</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.snes</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.snes</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.snes</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.snes</string>
				</dict>
			</array>
		</dict>
		<key>string-single</key>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.snes</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.snes</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.snes</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.snes</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.snes</string>
	<key>uuid</key>
	<string>D70C75B8-41C7-4CAC-B3DE-F978EBB06F5E</string>
</dict>
</plist>
